# Generated by Django 4.0.5 on 2022-08-01 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_employee_taskstatus_employeetask'),
    ]

    operations = [
        migrations.CreateModel(
            name='userTasks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_data', models.CharField(max_length=200)),
            ],
        ),
    ]
