# Generated by Django 4.0.5 on 2022-08-01 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_usertasks'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeetask',
            name='taskid',
            field=models.IntegerField(default=0),
        ),
    ]
